import type { Metadata } from 'next';
import { Suspense } from 'react';
import { Inter } from 'next/font/google';
import './globals.scss';
import Header from '@/components/Header/Header';
import { ThemeProvider } from '@/contexts/ThemeContext/ThemeContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) => (
	<html lang='en'>
		<body className={`${inter.className} antialiased`}>
			<ThemeProvider>
				<Header />
				<Suspense fallback={<div>Loading...</div>}>
					{children}
				</Suspense>
			</ThemeProvider>
		</body>
	</html>
);

export default RootLayout;

